---
title: "Survival_QE_Cox"
author: "Chengyu_Du"
date: "2026-06-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(dplyr)
library(rstpm2)
library(flexsurv)
library(splines)
```

```{r}
dat <- readRDS("output/dat_clean.rds")
```


```{r}
dat$nyha_nominal <- factor(
  dat$nyha_class,
  levels = c("I", "II", "III", "IV"),
  ordered = FALSE
)

dat$nyha_score <- as.numeric(dat$nyha_nominal)
```

```{r}
surv_obj <- Surv(
  time = dat$time,
  event = dat$status
)
```



```{r}
cox_nyha <- coxph(
  surv_obj ~ nyha_nominal,
  data = dat
)

summary(cox_nyha)
```


```{r}
ph_nyha <- cox.zph(cox_nyha,terms = FALSE)

ph_nyha
```


```{r}
cox_clinical <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + log(creatinine) + sodium,
  data = dat
)

summary(cox_clinical)
```

```{r}
cox_age_df2 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    ns(age, df = 2) + gender + bmi + smoking + diabetes +
    ejection_fraction + log(creatinine) + sodium,
  data = dat
)

cox_age_df3 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    ns(age, df = 3) + gender + bmi + smoking + diabetes +
    ejection_fraction + log(creatinine) + sodium,
  data = dat
)

AIC(cox_clinical, cox_age_df2, cox_age_df3)
anova(cox_clinical, cox_age_df2, test = "LRT")
anova(cox_age_df2, cox_age_df3, test = "LRT")
```

```{r}
cox_bmi_df2 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + ns(bmi, df = 2) + smoking + diabetes +
    ejection_fraction + log(creatinine) + sodium,
  data = dat
)

cox_bmi_df3 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + ns(bmi, df = 3) + smoking + diabetes +
    ejection_fraction + log(creatinine) + sodium,
  data = dat
)

AIC(cox_clinical, cox_bmi_df2, cox_bmi_df3)
anova(cox_clinical, cox_bmi_df2, test = "LRT")
anova(cox_bmi_df2, cox_bmi_df3, test = "LRT")
```

```{r}
cox_ef_df2 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ns(ejection_fraction, df = 2) + log(creatinine) + sodium,
  data = dat
)

cox_ef_df3 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ns(ejection_fraction, df = 3) + log(creatinine) + sodium,
  data = dat
)

AIC(cox_clinical, cox_ef_df2, cox_ef_df3)
anova(cox_clinical, cox_ef_df2, test = "LRT")
anova(cox_ef_df2, cox_ef_df3, test = "LRT")
```

```{r}
cox_creatinine_df2 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat
)

cox_creatinine_df3 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 3) + sodium,
  data = dat
)

AIC(cox_clinical, cox_creatinine_df2, cox_creatinine_df3)
anova(cox_clinical, cox_creatinine_df2, test = "LRT")
anova(cox_creatinine_df2, cox_creatinine_df3, test = "LRT")
```

```{r}
cox_sodium_df2 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + log(creatinine) + ns(sodium, df = 2),
  data = dat
)

cox_sodium_df3 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + log(creatinine) + ns(sodium, df = 3),
  data = dat
)

AIC(cox_clinical, cox_sodium_df2, cox_sodium_df3)
anova(cox_clinical, cox_sodium_df2, test = "LRT")
anova(cox_sodium_df2, cox_sodium_df3, test = "LRT")
```

```{r}
cox_spline_all <- coxph(
  Surv(time, status) ~ nyha_nominal +
    ns(age, df = 3) + gender + ns(bmi, df = 3) +
    smoking + diabetes + ns(ejection_fraction, df = 3) +
    ns(log(creatinine), df = 3) + ns(sodium, df = 3),
  data = dat
)

AIC(cox_clinical, cox_spline_all)
anova(cox_clinical, cox_spline_all, test = "LRT")
```

```{r}
summary(cox_spline_all)
```


```{r}
cox_clinical2 <- coxph(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat
)

AIC(cox_clinical, cox_clinical2)
#summary(cox_clinical2)
```

```{r}
ph_clinical <- cox.zph(cox_clinical2,terms = FALSE)
ph_clinical
```



```{r}
par(mfrow = c(1, 3))
par(mar = c(4.2, 4.2, 2.2, 1.0))

plot(
  ph_clinical[1],
  main = "NYHA II vs I",
  xlab = "Time",
  ylab = "Beta"
)

plot(
  ph_clinical[2],
  main = "NYHA III vs I",
  xlab = "Time",
  ylab = "Beta"
)

plot(
  ph_clinical[3],
  main = "NYHA IV vs I",
  xlab = "Time",
  ylab = "Beta"
)

par(mfrow = c(1, 1))
```




```{r}
#Now Consider Time-Varing Cox
dat$nyha_II <- as.numeric(dat$nyha_nominal == "II")
dat$nyha_III <- as.numeric(dat$nyha_nominal == "III")
dat$nyha_IV <- as.numeric(dat$nyha_nominal == "IV")
```

```{r}
#Original Cox
cox_base <- coxph(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat
)

```

```{r}
#g(t) = t
cox_tv_t <- coxph(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium +
    tt(nyha_II) + tt(nyha_III) + tt(nyha_IV),
  data = dat,
  tt = function(x, t, ...) x * t
)

#summary(cox_tv_t)
```

```{r}
#g(t) = logt
cox_tv_log <- coxph(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium +
    tt(nyha_II) + tt(nyha_III) + tt(nyha_IV),
  data = dat,
  tt = function(x, t, ...) x * log(t)
)

#summary(cox_tv_log)
```

```{r}
#g(t) = log(1+t)
cox_tv_log1 <- coxph(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium +
    tt(nyha_II) + tt(nyha_III) + tt(nyha_IV),
  data = dat,
  tt = function(x, t, ...) x * log(1 + t)
)

#summary(cox_tv_log1)
```

```{r}
# AIC Comparision
AIC(
  cox_base,
  cox_tv_t,
  cox_tv_log,
  cox_tv_log1
)
```

```{r}
ll_base <- as.numeric(logLik(cox_base))

ll_t <- as.numeric(logLik(cox_tv_t))
ll_log <- as.numeric(logLik(cox_tv_log))
ll_log1 <- as.numeric(logLik(cox_tv_log1))

lr_t <- 2 * (ll_t - ll_base)
lr_log <- 2 * (ll_log - ll_base)
lr_log1 <- 2 * (ll_log1 - ll_base)

p_t <- pchisq(lr_t, df = 3, lower.tail = FALSE)
p_log <- pchisq(lr_log, df = 3, lower.tail = FALSE)
p_log1 <- pchisq(lr_log1, df = 3, lower.tail = FALSE)

tv_compare <- data.frame(
  model = c("NYHA x t", "NYHA x log(t)", "NYHA x log(1+t)"),
  logLik = c(ll_t, ll_log, ll_log1),
  LR = c(lr_t, lr_log, lr_log1),
  df = 3,
  p_value = c(p_t, p_log, p_log1),
  AIC = c(
    AIC(cox_tv_t),
    AIC(cox_tv_log),
    AIC(cox_tv_log1)
  )
)

tv_compare
```




```{r}
# Flexible parametric survival model

rp_clinical <- stpm2(
  Surv(time, status) ~ nyha_nominal +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat,
  df = 4
)

#summary(rp_clinical)

AIC(rp_clinical)
```
```{r}
rp_base <- stpm2(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat,
  df = 4
)

#summary(rp_base)
AIC(rp_base)
```

```{r}
rp_tvc1 <- stpm2(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat,
  df = 4,
  tvc = list(
    nyha_II = 1,
    nyha_III = 1,
    nyha_IV = 1
  )
)

#summary(rp_tvc1)
AIC(rp_tvc1)
```
```{r}
rp_tvc2 <- stpm2(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat,
  df = 4,
  tvc = list(
    nyha_II = 2,
    nyha_III = 2,
    nyha_IV = 2
  )
)

#summary(rp_tvc2)
AIC(rp_tvc2)
```

```{r}
rp_tvc3 <- stpm2(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium,
  data = dat,
  df = 4,
  tvc = list(
    nyha_II = 3,
    nyha_III = 3,
    nyha_IV = 3
  )
)

#summary(rp_tvc3)
AIC(rp_tvc3)
```


```{r}
AIC(
  rp_base,
  rp_tvc1,
  rp_tvc2,
  rp_tvc3
)
```

```{r}
#anova(rp_tvc1, rp_base)
#anova(rp_tvc2, rp_tvc1)
#anova(rp_tvc3, rp_tvc2)
```



```{r}
# Values held fixed for plotting
time_grid <- seq(1, 48, length.out = 120)

pred_ref <- data.frame(
  time = time_grid,
  nyha_II = 0,
  nyha_III = 0,
  nyha_IV = 0,
  age = median(dat$age),
  gender = factor("Female", levels = levels(dat$gender)),
  bmi = median(dat$bmi),
  smoking = factor("Never", levels = levels(dat$smoking)),
  diabetes = factor("No", levels = levels(dat$diabetes)),
  ejection_fraction = median(dat$ejection_fraction),
  creatinine = median(dat$creatinine),
  sodium = median(dat$sodium)
)
```

```{r}
pdf("figures/rp_time_varying_hr.pdf", width = 9, height = 3.2)

par(mfrow = c(1, 3))
par(mar = c(4.2, 4.2, 2.2, 1.0))

plot(rp_tvc1, newdata = pred_ref, type = "hr",
     exposed = function(x) { x$nyha_II <- 1; x },
     xlab = "Time (months)", ylab = "Adjusted hazard ratio",
     main = "NYHA II vs I",rug = FALSE)
abline(h = 1, lty = 2, col = "grey45")

plot(rp_tvc1, newdata = pred_ref, type = "hr",
     exposed = function(x) { x$nyha_III <- 1; x },
     xlab = "Time (months)", ylab = "Adjusted hazard ratio",
     main = "NYHA III vs I",rug = FALSE)
abline(h = 1, lty = 2, col = "grey45")

plot(rp_tvc1, newdata = pred_ref, type = "hr",
     exposed = function(x) { x$nyha_IV <- 1; x },
     xlab = "Time (months)", ylab = "Adjusted hazard ratio",
     main = "NYHA IV vs I",rug = FALSE)
abline(h = 1, lty = 2, col = "grey45")

dev.off()

par(mfrow = c(1, 1))
```
```{r}
rp_tvc_gene <- stpm2(
  Surv(time, status) ~ nyha_II + nyha_III + nyha_IV +
    age + gender + bmi + smoking + diabetes +
    ejection_fraction + ns(log(creatinine), df = 2) + sodium +
    GENE_001 + GENE_002 + GENE_005 + GENE_024,
  data = dat,
  df = 4,
  tvc = list(
    nyha_II = 1,
    nyha_III = 1,
    nyha_IV = 1
  )
)


```

```{r}
AIC(rp_base, rp_tvc1, rp_tvc_gene)
```

```{r}
pred_ref_gene <- pred_ref

pred_ref_gene$GENE_001 <- 0
pred_ref_gene$GENE_002 <- 0
pred_ref_gene$GENE_005 <- 0
pred_ref_gene$GENE_024 <- 0

par(mfrow = c(1, 3))
par(mar = c(4.2, 4.2, 2.8, 1.0))

plot(
  rp_tvc_gene,
  newdata = pred_ref_gene,
  type = "hr",
  exposed = function(x) {
    x$nyha_II <- 1
    x$nyha_III <- 0
    x$nyha_IV <- 0
    x
  },
  ci = FALSE,
  rug = FALSE,
  main = "NYHA II vs I",
  xlab = "Time",
  ylab = "Hazard ratio"
)
abline(h = 1, lty = 2, col = "grey45")

plot(
  rp_tvc_gene,
  newdata = pred_ref_gene,
  type = "hr",
  exposed = function(x) {
    x$nyha_II <- 0
    x$nyha_III <- 1
    x$nyha_IV <- 0
    x
  },
  ci = FALSE,
  rug = FALSE,
  main = "NYHA III vs I",
  xlab = "Time",
  ylab = "Hazard ratio"
)
abline(h = 1, lty = 2, col = "grey45")

plot(
  rp_tvc_gene,
  newdata = pred_ref_gene,
  type = "hr",
  exposed = function(x) {
    x$nyha_II <- 0
    x$nyha_III <- 0
    x$nyha_IV <- 1
    x
  },
  ci = FALSE,
  rug = FALSE,
  main = "NYHA IV vs I",
  xlab = "Time",
  ylab = "Hazard ratio"
)
abline(h = 1, lty = 2, col = "grey45")
```
```{r}
cox_selected_gene <- coxph(
  Surv(time, status) ~ nyha_nominal + age + gender + bmi +
    smoking + diabetes + ejection_fraction + ns(log(creatinine), df = 2) + sodium +
    GENE_001 + GENE_002 + GENE_005 + GENE_024,
  data = dat
)

summary(cox_selected_gene)
cox.zph(cox_selected_gene, terms = FALSE)
```



